# -*- mode: python -*-
# SCons build file (modified)
#from https://github.com/NobbZ/scons-latex/blob/master/SConstruct

import os


for basename in [x for x in os.listdir('.') if '.tex' in x]:
    basename = basename.replace('.tex', '')

    env = Environment(ENV = os.environ)

    # Use LuaTeX instead of pdfTeX.
    env.Replace(PDFLATEX='lualatex')

    # Use Biber instead of BiBTeX.
    env.Replace(BIBTEX='biber')

    # Look in standard directory ~/texmf for .sty files.
    env.SetDefault(TEXMFHOME=os.path.join(os.environ['HOME'], 'texmf'))


    pdf = env.PDF(basename + '.tex')
    env.Clean(pdf, basename + '.synctex.gz')
    env.Clean(pdf, basename + '.bbl')
    env.Clean(pdf, basename + '.bbg')
    Default(pdf)


    #tgt = env.Command(['res/target.pdf'], 'analyse.py', 'python3 analyse.py')
